# Generated by Django 5.1 on 2024-12-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_reviewrating_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
